spring:
  application:
    name: mq-service
  ## 配置zipkin地址 以及sleuth服务抓取日志的采样百分比
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9500
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      # 注册中心地址（集群时指定另外多个个注册中心地址）
      defaultZone: http://localhost:7001/eureka/