spring:
  profiles:
    active: prod
  application:
    name: zuul-gateway
  rabbitmq:     # 现在将集成RabbitMQ作为消息服务总线处理
    host: 106.12.213.251   # RabbitMQ主机服务地址
    port: 5672    # RabbitMQ的监听端口
    username: yangmi  # 用户名
    password: ym # 密码
  ## 配置zipkin地址 以及sleuth服务抓取日志的采样百分比
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9500
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 5001

# 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

##zuul路由配置:
zuul:
  routes:
    # 河长通业务
    hzt:
      path: /hzt/**
      serviceId: hztserver
    # 文件服务
    fdfs:
      path: /fdfs/**
      serviceId: fdfs-service
    # 消息服务
    mq:
      path: /mq/**
      serviceId: mq-service
    # 忽略所有服务名
  ignored-services: "*"
  ## 关闭前缀忽略功能
  strip-prefix: false
  # 处理http请求头为空的问题
  sensitive-headers:

# bus-config服务器端刷新地址 http://localhost:4001/actuator/bus-refresh
# bus-config客户端刷新地址http://localhost:4001/actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-detail:  always